//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PsychoLab.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExportLog
    {
        public int LogID { get; set; }
        public System.DateTime ExportDate { get; set; }
        public string FormatExported { get; set; }
    
        public virtual User User { get; set; }
    }
}
