//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PsychoLab.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PsychologistReport
    {
        public int ReportID { get; set; }
        public int SessionID { get; set; }
        public string ReportContent { get; set; }
        public System.DateTime PrintDate { get; set; }
    
        public virtual Schedule Schedule { get; set; }
    }
}
