//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PsychoLab.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestResult
    {
        public int ResultID { get; set; }
        public Nullable<int> SessionID { get; set; }
        public Nullable<int> TestID { get; set; }
        public Nullable<int> QuestionID { get; set; }
        public Nullable<int> AnswerID { get; set; }
    
        public virtual PsychologicalTest PsychologicalTest { get; set; }
        public virtual Schedule Schedule { get; set; }
        public virtual TestAnswer TestAnswer { get; set; }
        public virtual TestQuestion TestQuestion { get; set; }
    }
}
